In [1]:
import pandas as pd

In [2]:
dff=pd.read_csv('yelp_academic_dataset_review.csv')
dff.head()

,business_id,cool,date,funny,review_id,stars,text,type,useful,user_id
0,2aFiy99vNLklCx3T_tGS9A,0,2011-10-10,0,NxL8SIC5yqOdnlXCg18IBg,5.0,If you enjoy service by someone who is as comp...,review,0.0,KpkOkG6RIf4Ra25Lhhxf1A
1,2aFiy99vNLklCx3T_tGS9A,0,2010-12-29,0,pXbbIgOXvLuTi_SPs1hQEQ,5.0,After being on the phone with Verizon Wireless...,review,1.0,bQ7fQq1otn9hKX-gXRsrgA
2,2aFiy99vNLklCx3T_tGS9A,0,2011-04-29,0,wslW2Lu4NYylb1jEapAGsw,5.0,Great service! Corey is very service oriented....,review,0.0,r1NUhdNmL6yU9Bn-Yx6FTw
3,2LfIuF3_sX6uwe-IR-P0jQ,1,2014-07-14,0,GP6YEearUWrzPtQYSF1vVg,5.0,Highly recommended. Went in yesterday looking ...,review,0.0,aW3ix1KNZAvoM8q-WghA3Q
4,2LfIuF3_sX6uwe-IR-P0jQ,0,2014-01-15,0,25RlYGq2s5qShi-pn3ufVA,4.0,I walked in here looking for a specific piece ...,review,0.0,YOo-Cip8HqvKp_p9nEGphw

In [3]:
dff=pd.read_csv('yelp_academic_dataset_business.csv')
dff.head(2)

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,neighborhood,postal_code,review_count,stars,state,type
0,"227 E Baseline Rd, Ste J2","['BikeParking: True', 'BusinessAcceptsBitcoin:...",0DI8Dt2PJp07XkVvIElIcQ,"['Tobacco Shops', 'Nightlife', 'Vape Shops', '...",Tempe,"['Monday 11:0-21:0', 'Tuesday 11:0-21:0', 'Wed...",0,33.378214,-111.936102,Innovative Vapors,NaN,85283,17,4.5,AZ,business
1,495 S Grand Central Pkwy,"['BusinessAcceptsBitcoin: False', 'BusinessAcc...",LTlCaCGZE14GuaUXUGbamg,"['Caterers', 'Grocery', 'Food', 'Event Plannin...",Las Vegas,"['Monday 0:0-0:0', 'Tuesday 0:0-0:0', 'Wednesd...",1,36.192284,-115.159272,Cut and Taste,NaN,89106,9,5.0,NV,business

In [10]:
# read the entire file into a python array
with open("yelp_academic_dataset_business.json", 'r',encoding="utf8") as f:
    data = f.readlines()

# remove the trailing "\n" from each line
data = map(lambda x: x.rstrip(), data)


data_json_str = "[" + ','.join(data) + "]"

# now, load it into pandas
data_df = pd.read_json(data_json_str)

data_df.to_csv('yelp_academic_dataset_business_1.csv', sep=',', encoding='utf-8', index=False)

dff=pd.read_csv('yelp_academic_dataset_business_1.csv')
dff.head(2)

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,neighborhood,postal_code,review_count,stars,state,type
0,"227 E Baseline Rd, Ste J2","['BikeParking: True', 'BusinessAcceptsBitcoin:...",0DI8Dt2PJp07XkVvIElIcQ,"['Tobacco Shops', 'Nightlife', 'Vape Shops', '...",Tempe,"['Monday 11:0-21:0', 'Tuesday 11:0-21:0', 'Wed...",0,33.378214,-111.936102,Innovative Vapors,NaN,85283,17,4.5,AZ,business
1,495 S Grand Central Pkwy,"['BusinessAcceptsBitcoin: False', 'BusinessAcc...",LTlCaCGZE14GuaUXUGbamg,"['Caterers', 'Grocery', 'Food', 'Event Plannin...",Las Vegas,"['Monday 0:0-0:0', 'Tuesday 0:0-0:0', 'Wednesd...",1,36.192284,-115.159272,Cut and Taste,NaN,89106,9,5.0,NV,business

In [7]:
from __future__ import print_function
from tqdm import tqdm
import unicodecsv as csv
import ast
from collections import defaultdict
import json

print("Reading data from JSON...")
data = list()
with open("yelp_academic_dataset_business.json", 'r',encoding="utf8") as f:
    for line in f:
        data.append(json.loads(line))


print("Calculating all categories represented in the data...")
all_categories = []
for row in data:
    if row['categories']:
        all_categories += row['categories']
all_categories = set(all_categories)

print("Calculating all attributes represented in the data...")
all_attributes = []
attributes_with_subattributes = defaultdict(lambda: set())
for row in data:
    if row['attributes']:
        for attribute_string in row['attributes']:
            attribute = attribute_string.split(':')[0]
            value = ':'.join(attribute_string.split(':')[1:])
            value = value.strip()
            all_attributes.append(attribute)
            if '{' in value:
                attribute_data = ast.literal_eval(value)
                for subattribute, v in attribute_data.items():
                    attributes_with_subattributes[attribute].add(subattribute)                
all_attributes = set(all_attributes)
print("Found these attributes with sub-attributes:")
for attribute, subattributes in attributes_with_subattributes.items():
    print('%s: %s' % (attribute, ', '.join(subattributes)))


print("Writing attributes to file...")
with open('yelp_academic_dataset_business-attributes.txt', 'w') as f:
    f.write('\n'.join(sorted(list(all_attributes))))

print("Writing categories to file...")
with open('yelp_academic_dataset_business-categories.txt', 'w') as f:
    f.write('\n'.join(sorted(list(all_categories))))

print("Processing data...")
new_data = list()
for row in tqdm(data):
    new_row = {}
    for k, v in row.items():
        if k not in ['hours', 'categories', 'attributes']:
            new_row[k] = v
        else:
            if k == 'hours' and row['hours']:
                for hour in row['hours']:
                    day, time_string = hour.split(' ')
                    new_row['hours_' + day] = time_string
            elif k == 'attributes' and row['attributes']:
                attributes = defaultdict(lambda: dict())
                for attribute_string in row['attributes']:
                    attribute = attribute_string.split(':')[0]
                    value = ':'.join(attribute_string.split(':')[1:])
                    value = value.strip()
                    if '{' in value:
                        data = ast.literal_eval(value)
                        for subattribute, subattribute_value in data.items():
                            attributes[attribute][subattribute] = subattribute_value
                    else:
                        attributes[attribute] = value
                for attribute in all_attributes:
                    if attribute in attributes_with_subattributes:
                        for subattribute in attributes_with_subattributes[attribute]:
                            subattributes = attributes.get(attribute, dict())
                            new_row['attribute_' + attribute + '_' + subattribute] = subattributes.get(subattribute, False)
                    else:
                        new_row['attribute_' + attribute] = attributes.get(attribute, False)
            elif k == 'categories' and row['categories']:
                new_row['categories'] = ', '.join(sorted(row['categories']))
#                for category in all_categories:
#                    new_row['category_' + category] = (category in row['categories'])
    new_data.append(new_row)

print("Writing data to CSV file...")
with open('yelp_academic_dataset_business.csv', 'wb') as f:
    fieldnames = sorted(new_data[0].keys())
    dw = csv.DictWriter(f, fieldnames=fieldnames, encoding='UTF-8')
    dw.writeheader()
    dw.writerows(new_data)

Reading data from JSON...
Calculating all categories represented in the data...
Calculating all attributes represented in the data...
Found these attributes with sub-attributes:
BusinessParking: garage, street, validated, lot, valet
Ambience: upscale, intimate, romantic, classy, divey, casual, trendy, hipster, touristy
GoodForMeal: latenight, brunch, dinner, lunch, dessert, breakfast
HairSpecializesIn: perms, curly, asian, straightperms, africanamerican, kids, extensions, coloring
BestNights: sunday, saturday, monday, tuesday, wednesday, friday, thursday
Music: video, dj, live, background_music, karaoke, jukebox, no_music
DietaryRestrictions: vegetarian, soy-free, vegan, dairy-free, kosher, gluten-free, halal
Writing attributes to file...
Writing categories to file...
Processing data...

100%|████████████████████████████████████████████████████████████████████████| 144072/144072 [00:23<00:00, 6045.02it/s]

Writing data to CSV file...

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import pickle

import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim